import Head from 'next/head'

import Hero from '../components/sections/Hero'
import About from '../components/sections/About'

export default function Home() {
  return (
    <div>
      <Head>
        <title>Create Next App</title>
        <meta name='description' content='Generated by create next app' />
        <link rel='icon' href='/favicon.ico' />
      </Head>

      <Hero />
      <About />
    </div>
  )
}
